name: Linux CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '!src/osx/**'
      - '!src/freebsd/**'
      - 'include/**'
      - 'CMakeLists.txt'
      - '.github/workflows/linux.yml'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container: alpine:edge
    strategy:
      matrix:
        compiler: ["g++", "clang++"]

    steps:
      - name: Install LLVM build tools
        if: ${{ matrix.compiler == 'clang++' }}
        run: apk add --update --no-cache clang cmake ninja

      - name: Install GCC build tools
        if: ${{ matrix.compiler == 'g++' }}
        run: apk add --update --no-cache cmake g++ ninja

      - name: Checkout source
        uses: actions/checkout@v3

      - name: Configure
        run: CXX=${{ matrix.compiler }} cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DBTOP_GPU=NO -DBTOP_STATIC=ON

      - name: Build
        run: cmake --build build -v

