name: MacOS CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '!src/linux/**'
      - '!src/freebsd/**'
      - 'include/**'
      - 'CMakeLists.txt'
      - '.github/workflows/macos.yml'

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install build tools
        run: brew install llvm@17 ninja

      - name: Configure
        run: |
          export CXX="$(brew --prefix llvm)/bin/clang++"
          export CPPFLAGS="-I$(brew --prefix llvm)/include"
          export LDFLAGS="-L$(brew --prefix llvm)/lib -L$(brew --prefix llvm)/lib/c++ -Wl,-rpath,$(brew --prefix llvm)/lib/c++ -fuse-ld=$(brew --prefix llvm)/bin/ld64.lld"
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build -v

